version: '3'
services:
  diffusionlm:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
